export const ADD_FLASH_MESSAGE    = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const GET_CLIENTS_LIST     = 'GET_CLIENTS_LIST';
export const REGISTER_NEW_CLIENT  = 'REGISTER_NEW_CLIENT';

export const SET_CURRENT_USER     = 'SET_CURRENT_USER';
